version: "3.9"

services:
  db:
    image: postgres:16
    container_name: bot_insta_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    
  bot:
    build: .
    container_name: telegram_insta_bot
    restart: always
    depends_on:
      - db
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}  
      TOKEN: ${TOKEN}
      IG_USERNAME: ${IG_USERNAME}
      IG_PASSWORD: ${IG_PASSWORD}
      SESSION: ${SESSION}
    volumes:
      - ./sessions:/app/sessions
    ports:
      - "8003:8000"

volumes:
  pgdata:
